apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-central-sonar-vault-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-central-sonar-vault-01
  template:
    metadata:
      labels:
        app: test-central-sonar-vault-01
    spec:
      containers:
        - name: test-central-sonar-vault-01
          image: sureshmavp1/test-central-sonar-vault-01:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000