apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-repo-02
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-test-repo-02
spec:
  project: default
  source:
    repoURL: https://github.com/Backstage-IDP-PoC/k8s-manifests.git
    targetRevision: main
    path: apps/python-test-repo-02
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id
    ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id  
