apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-repo-02
  labels:
    backstage.io/kubernetes-id: python-test-repo-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test-repo-02
  template:
    metadata:
      labels:
        app: python-test-repo-02
        backstage.io/kubernetes-id: python-test-repo-02
    spec:
      containers:
        - name: python-test-repo-02
          image: sureshmavp1/python-test-repo-02:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000