apiVersion: v1
kind: Service
metadata:
  name: dev-repo-onboarding-mar-30-test2
spec:
  selector:
    app: dev-repo-onboarding-mar-30-test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dev-repo-onboarding-mar-30-test2-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: dev-repo-onboarding-mar-30-test2.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dev-repo-onboarding-mar-30-test2
#             port:
#               number: 80