apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-python-test-repo-04
  namespace: prod
  labels:
    app: sm-python-test-repo-04
    backstage.io/kubernetes-id: sm-python-test-repo-04
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-python-test-repo-04
  template:
    metadata:
      labels:
        app: sm-python-test-repo-04
        backstage.io/kubernetes-id: sm-python-test-repo-04
        environment: prod
    spec:
      containers:
        - name: sm-python-test-repo-04
          image: sureshmavp1/sm-python-test-repo-04:1.0.1
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "prod"