apiVersion: v1
kind: Service
metadata:
  name: docker-compose-apr17-test2
spec:
  selector:
    app: docker-compose-apr17-test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer