apiVersion: v1
kind: Service
metadata:
  name: ssp-demo1-mar17
spec:
  selector:
    app: ssp-demo1-mar17
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer