apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-01
  labels:
    backstage.io/kubernetes-id: vault-demo-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo-01
  template:
    metadata:
      labels:
        app: vault-demo-01
        backstage.io/kubernetes-id: vault-demo-01
    spec:
      containers:
        - name: vault-demo-01
          image: sureshmavp1/vault-demo-01:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000