apiVersion: v1
kind: Service
metadata:
  name: gssp-app2-mar18
spec:
  selector:
    app: gssp-app2-mar18
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer