apiVersion: apps/v1
kind: Deployment
metadata:
  name: app6-sm-mar10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app6-sm-mar10
  template:
    metadata:
      labels:
        app: app6-sm-mar10
    spec:
      containers:
        - name: app6-sm-mar10
          image: sureshmavp1/app6-sm-mar10:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000