apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-demo-test-01-27-apr
  labels:
    backstage.io/kubernetes-id: gssp-demo-test-01-27-apr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-demo-test-01-27-apr
  template:
    metadata:
      labels:
        app: gssp-demo-test-01-27-apr
        backstage.io/kubernetes-id: gssp-demo-test-01-27-apr
    spec:
      containers:
        - name: gssp-demo-test-01-27-apr
          image: sureshmavp1/gssp-demo-test-01-27-apr:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000