apiVersion: v1
kind: Service
metadata:
  name: app11-sm-mar12
spec:
  selector:
    app: app11-sm-mar12
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer