apiVersion: v1
kind: Service
metadata:
  name: sonar-24-apr-05
spec:
  selector:
    app: sonar-24-apr-05
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer