apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-apr1-test3
  labels:
    backstage.io/kubernetes-id: gssp-apr1-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-apr1-test3
  template:
    metadata:
      labels:
        app: gssp-apr1-test3
        backstage.io/kubernetes-id: gssp-apr1-test3
    spec:
      containers:
        - name: gssp-apr1-test3
          image: sureshmavp1/gssp-apr1-test3:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000