apiVersion: v1
kind: Service
metadata:
  name: vault-test-03-27-apr
spec:
  selector:
    app: vault-test-03-27-apr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer