apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-test-repo-20th-apr-1
  labels:
    backstage.io/kubernetes-id: dev-test-repo-20th-apr-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-test-repo-20th-apr-1
  template:
    metadata:
      labels:
        app: dev-test-repo-20th-apr-1
        backstage.io/kubernetes-id: dev-test-repo-20th-apr-1
    spec:
      containers:
        - name: dev-test-repo-20th-apr-1
          image: sureshmavp1/dev-test-repo-20th-apr-1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000