apiVersion: v1
kind: Service
metadata:
  name: app-argo1-march16
spec:
  selector:
    app: app-argo1-march16
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer