apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-repo-onboarding-mar-30-test5
  labels:
    backstage.io/kubernetes-id: dev-repo-onboarding-mar-30-test5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-repo-onboarding-mar-30-test5
  template:
    metadata:
      labels:
        app: dev-repo-onboarding-mar-30-test5
        backstage.io/kubernetes-id: dev-repo-onboarding-mar-30-test5
    spec:
      containers:
        - name: dev-repo-onboarding-mar-30-test5
          image: sureshmavp1/dev-repo-onboarding-mar-30-test5:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000