apiVersion: apps/v1
kind: Deployment
metadata:
  name: app7-sm-mar10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app7-sm-mar10
  template:
    metadata:
      labels:
        app: app7-sm-mar10
    spec:
      containers:
        - name: app7-sm-mar10
          image: sureshmavp1/app7-sm-mar10:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000