apiVersion: v1
kind: Service
metadata:
  name: app7-sm-mar10
spec:
  selector:
    app: app7-sm-mar10
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer