apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-march16-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-march16-demo
  template:
    metadata:
      labels:
        app: app-march16-demo
    spec:
      containers:
        - name: app-march16-demo
          image: sureshmavp1/app-march16-demo:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000