apiVersion: v1
kind: Service
metadata:
  name: app-march16-demo
spec:
  selector:
    app: app-march16-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer