apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-18-apr-repo-test-01
  namespace: prod
  labels:
    app: sm-18-apr-repo-test-01
    backstage.io/kubernetes-id: sm-18-apr-repo-test-01
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-18-apr-repo-test-01
  template:
    metadata:
      labels:
        app: sm-18-apr-repo-test-01
        backstage.io/kubernetes-id: sm-18-apr-repo-test-01
        environment: prod
    spec:
      containers:
        - name: sm-18-apr-repo-test-01
          image: sureshmavp1/sm-18-apr-repo-test-01:1.0.5
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "prod"