apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-dockerized-30-apr-03
  labels:
    backstage.io/kubernetes-id: gssp-dockerized-30-apr-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-dockerized-30-apr-03
  template:
    metadata:
      labels:
        app: gssp-dockerized-30-apr-03
        backstage.io/kubernetes-id: gssp-dockerized-30-apr-03
    spec:
      containers:
        - name: gssp-dockerized-30-apr-03
          image: sureshmavp1/gssp-dockerized-30-apr-03:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000