apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-ssp-mar17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-ssp-mar17
  template:
    metadata:
      labels:
        app: app1-ssp-mar17
    spec:
      containers:
        - name: app1-ssp-mar17
          image: sureshmavp1/app1-ssp-mar17:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000