apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
  labels:
    backstage.io/component: 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: /manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
