apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-version-1-1-test01
  labels:
    backstage.io/kubernetes-id: gssp-version-1-1-test01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-version-1-1-test01
  template:
    metadata:
      labels:
        app: gssp-version-1-1-test01
        backstage.io/kubernetes-id: gssp-version-1-1-test01
    spec:
      containers:
        - name: gssp-version-1-1-test01
          image: sureshmavp1/gssp-version-1-1-test01:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000