apiVersion: v1
kind: Service
metadata:
  name: sonar-vault-demo-apr-27-02
spec:
  selector:
    app: sonar-vault-demo-apr-27-02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: sonar-vault-demo-apr-27-02-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: sonar-vault-demo-apr-27-02.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: sonar-vault-demo-apr-27-02
#             port:
#               number: 80