apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-dockerized-30-apr-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-dockerized-30-apr-04
  template:
    metadata:
      labels:
        app: gssp-dockerized-30-apr-04
    spec:
      containers:
        - name: gssp-dockerized-30-apr-04
          image: sureshmavp1/gssp-dockerized-30-apr-04:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000